spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8081